In [1]:
import csv
import pandas as pd
import pickle

In [2]:
with open("../SS-Twitter/raw.pickle", 'rb') as f:
    x = pickle.load(f)

In [3]:
x.keys()

dict_keys(['info', 'texts', 'val_ind', 'test_ind', 'train_ind'])

In [4]:
x['test_ind']

[1611,
 1881,
 1100,
 562,
 491,
 1171,
 865,
 526,
 1848,
 202,
 1349,
 1667,
 1104,
 2072,
 1672,
 1650,
 651,
 1127,
 1442,
 1941,
 41,
 1094,
 60,
 564,
 1239,
 1095,
 987,
 253,
 449,
 1205,
 530,
 1475,
 1089,
 1488,
 1960,
 1467,
 1556,
 744,
 509,
 747,
 1669,
 1225,
 907,
 1481,
 1227,
 580,
 165,
 1559,
 766,
 1326,
 231,
 107,
 395,
 1832,
 677,
 1708,
 365,
 982,
 76,
 1369,
 1790,
 1517,
 699,
 1916,
 667,
 1469,
 442,
 652,
 225,
 93,
 116,
 473,
 1977,
 1837,
 1818,
 1228,
 935,
 1579,
 154,
 1753,
 1014,
 723,
 498,
 942,
 1281,
 1378,
 9,
 1106,
 1504,
 83,
 64,
 122,
 532,
 1800,
 1486,
 561,
 460,
 1018,
 1271,
 1346,
 1585,
 1493,
 850,
 1761,
 2071,
 1575,
 1572,
 914,
 92,
 1639,
 269,
 1929,
 1738,
 1110,
 1701,
 2041,
 335,
 282,
 1686,
 574,
 1435,
 1741,
 2046,
 769,
 522,
 112,
 1919,
 754,
 300,
 55,
 1557,
 262,
 1260,
 2022,
 577,
 958,
 965,
 1747,
 1698,
 621,
 1400,
 1499,
 1640,
 1463,
 1405,
 1535,
 768,
 1910,
 150,
 426,
 2010,
 1802,
 1393,
 139,
 1280,
 143,
 543,
 1268,
 1888,
 1924,
 1742,
 968,
 235,
 1148,
 1712,
 650,
 1008,
 852,
 1191,
 943,
 146,
 1062,
 204,
 1870,
 1226,
 1732,
 1978,
 581,
 1892,
 1333,
 1248,
 906,
 1688,
 1141,
 172,
 160,
 2007,
 638,
 448,
 782,
 1956,
 1077,
 3,
 1543,
 1656,
 353,
 37,
 1058,
 1154,
 1551,
 1524,
 459,
 882,
 779,
 1374,
 783,
 1945,
 1285,
 918,
 727,
 873,
 1851,
 899,
 1996,
 1165,
 2100,
 1114,
 1540,
 397,
 704,
 869,
 414,
 608,
 1308,
 687,
 856,
 992,
 33,
 1339,
 256,
 275,
 1429,
 1188,
 1577,
 2084,
 1460,
 2035,
 78,
 171,
 1182,
 1137,
 1675,
 43,
 1953,
 1566,
 374,
 1999,
 771,
 1838,
 737,
 2081,
 2076,
 1118,
 359,
 1273,
 1827,
 617,
 611,
 2108,
 1820,
 99,
 572,
 905,
 1849,
 1920,
 419,
 2101,
 8,
 674,
 1709,
 1844,
 1983,
 110,
 1947,
 1178,
 1180,
 1224,
 963,
 815,
 1840,
 877,
 1366,
 267,
 297,
 286,
 1814,
 1756,
 1613,
 367,
 376,
 2024,
 966,
 1219,
 605,
 1283,
 1084,
 845,
 348,
 875,
 1984,
 465,
 1981,
 1117,
 501,
 223,
 1054,
 846,
 546,
 1007,
 1063,
 1602,
 126,
 1208,
 1841,
 1626,
 382,
 1457,
 1023,
 1691,
 998,
 1415,
 1476,
 243,
 273,
 1617,
 994,
 1598,
 1327,
 657,
 1330,
 1966,
 2030,
 1108,
 1649,
 313,
 1242,
 2025,
 249,
 80,
 1086,
 1578,
 1102,
 1541,
 504,
 1070,
 598,
 389,
 512,
 263,
 915,
 410,
 1685,
 817,
 1653,
 1979,
 1472,
 753,
 730,
 229,
 1586,
 318,
 1793,
 1432,
 1682,
 357,
 1474,
 212,
 5,
 1751,
 988,
 689,
 326,
 1160,
 615,
 1116,
 45,
 1775,
 659,
 1797,
 1032,
 1152,
 1451,
 1687,
 290,
 2083,
 912,
 467,
 443,
 1521,
 306,
 1749,
 536,
 2036,
 324,
 1388,
 17,
 1514,
 1970,
 147,
 1479,
 301,
 516,
 645,
 310,
 854,
 358,
 1930,
 1721,
 378,
 647,
 1523,
 337,
 2056,
 251,
 144,
 1139,
 1404,
 1745,
 1235,
 1357,
 649,
 1286,
 327,
 1932,
 311,
 1699,
 1952,
 1220,
 2054,
 1495,
 720,
 1593,
 837,
 201,
 1496,
 1589,
 1768,
 207,
 74,
 257,
 1530,
 1431,
 241,
 227,
 1553,
 1368,
 1184,
 892,
 986,
 2005,
 786,
 217,
 634,
 709,
 323,
 1440,
 312,
 293,
 1069,
 113,
 956,
 406,
 486,
 1316,
 1112,
 141,
 533,
 54,
 1135,
 1311,
 2002,
 508,
 1923,
 1522,
 1959,
 895,
 1197,
 897,
 1379,
 2045,
 493,
 678,
 999,
 1428,
 1123,
 240,
 1305,
 1238,
 1491,
 839,
 1666,
 1170,
 1857,
 1307,
 799,
 1204,
 1061,
 1198,
 197,
 738,
 1448,
 159,
 1584,
 211,
 1872,
 1132,
 1030,
 271,
 1552,
 752,
 1329,
 1931,
 10,
 1811,
 510,
 1240,
 1223,
 87,
 483,
 1652,
 627,
 1967,
 1437,
 2000,
 835,
 2021,
 381,
 1173,
 1985,
 1508,
 1006,
 1854,
 1992,
 1455,
 373,
 784,
 1020,
 314,
 1618,
 1290,
 1964,
 644,
 1282,
 930,
 1397,
 1003,
 30,
 2095,
 973,
 1001,
 610,
 555,
 541,
 1901,
 1113,
 46,
 1757,
 1546,
 830,
 694,
 458,
 1360,
 398,
 539,
 1891,
 1395,
 368,
 801,
 1162,
 1149,
 1244,
 1737,
 2031,
 1562,
 366,
 802,
 855,
 496,
 1209,
 1972,
 1264,
 989,
 886,
 800,
 794,
 1713,
 96,
 1354,
 494,
 1648,
 1059,
 471,
 415,
 798,
 662,
 547,
 1859,
 2096,
 478,
 26,
 653,
 71,
 1202,
 1266,
 1233,
 1403,
 1221,
 177,
 1908,
 19,
 675,
 946,
 1772,
 1534,
 453,
 210,
 1885,
 1158,
 1049,
 534,
 441,
 430,
 7,
 1401,
 157,
 1336,
 2029,
 632,
 640,
 1714,
 713,
 633,
 603,
 20,
 1458,
 1343,
 252,
 743,
 851,
 423,
 978,
 79,
 1884,
 953,
 928,
 479,
 1031,
 1446,
 1186,
 218,
 630,
 261,
 922,
 1987,
 1812,
 1501,
 84,
 1452,
 2052,
 940,
 187,
 1862,
 1237,
 1033,
 1628,
 158,
 1958,
 1622,
 42,
 1937,
 174,
 490,
 4,
 1427,
 407,
 773,
 1391,
 719,
 760,
 469,
 1722,
 1497,
 1660,
 1302,
 181,
 880,
 2080,
 796,
 1733,
 722,
 1718,
 792,
 363,
 1402,
 21,
 495,
 1419,
 485,
 1896,
 416,
 1810,
 1570,
 810,
 745,
 996,
 591,
 377,
 1462,
 1641,
 1902,
 726,
 515,
 1075,
 1215,
 1505,
 1935,
 1805,
 1502,
 691,
 1871,
 125,
 88,
 1498,
 1301,
 1287,
 1426,
 319,
 95,
 1087,
 246,
 643,
 1876,
 710,
 200,
 604,
 565,
 1471,
 1194,
 1724,
 1269,
 2091,
 1744,
 433,
 1175,
 646,
 1706,
 2051,
 104,
 1490,
 712,
 413,
 1199,
 1867,
 1671,
 549,
 1146,
 2042,
 663,
 1623,
 1988,
 153,
 972,
 1729,
 563,
 129,
 1624,
 1642,
 1465,
 50,
 1381,
 1363,
 75,
 1746,
 586,
 985,
 236,
 1252,
 361,
 40,
 355,
 1926,
 322,
 1090,
 233,
 343,
 669,
 1217,
 1071,
 1654,
 1946,
 1740,
 599,
 970,
 1222,
 325,
 952,
 2065,
 593,
 1051,
 360,
 969,
 696,
 1270,
 23,
 1321,
 584,
 818,
 1815,
 1036,
 1413,
 1785,
 1253,
 388,
 1728,
 848,
 883,
 1954,
 1809,
 167,
 1218,
 334,
 725,
 1615,
 1986,
 1774,
 1411,
 1921,
 1694,
 690,
 1101,
 1245,
 1203,
 1700,
 13,
 1500,
 1830,
 2014,
 1861,
 1526,
 824,
 2043,
 340,
 32,
 1183,
 1864,
 1289,
 1300,
 1246,
 1644,
 1882,
 1484,
 405,
 921,
 247,
 1477,
 748,
 105,
 1370,
 917,
 554,
 853,
 1789,
 341,
 1835,
 38,
 567,
 127,
 1464,
 16,
 622,
 1627,
 1576,
 601,
 1907,
 1786,
 1717,
 1681,
 750,
 132,
 234,
 179,
 1037,
 1255,
 1690,
 788,
 1620,
 435,
 597,
 585,
 63,
 487,
 1211,
 1659,
 1571,
 2032,
 309,
 260,
 1045,
 1236,
 1284,
 1704,
 1466,
 1990,
 672,
 209,
 248,
 2012,
 371,
 902,
 1678,
 1758,
 858,
 156,
 1043,
 97,
 481,
 408,
 573,
 777,
 292,
 387,
 1711,
 1121,
 27,
 1529,
 916,
 445,
 695,
 1297,
 427,
 844,
 1773,
 790,
 1005,
 428,
 1243,
 354,
 130,
 386,
 431,
 476,
 676,
 1200,
 1153,
 2075,
 1359,
 575,
 232,
 1913,
 1668,
 1109,
 57,
 502,
 1776,
 1674,
 595,
 648,
 1310,
 870,
 806,
 90,
 1957,
 866,
 715,
 1645,
 1024,
 1582,
 317,
 384,
 316,
 926,
 947,
 1373,
 993,
 1190,
 456,
 626,
 120,
 1765,
 781,
 298,
 1314,
 785,
 685,
 184,
 1394,
 2047,
 876,
 73,
 1608,
 609,
 425,
 2107,
 980,
 556,
 2077,
 1858,
 307,
 724,
 1365,
 ...]

In [5]:
train_set = pd.read_csv("partial_merged_utf_nonum.csv", encoding='utf-8', header=None)

In [6]:
train_set.head()

                                                   0
0  신곡 첫 해금 발매 히프 노 시스 마이크 권 완성 한정판 에 수록 되다 지로 이 시...
1               내 친구 어디 있다 나 는 슬프다 나르다 위로 하다 수 있다 부디
2                                             레드 벨벳
3                                       앞 으로도 많이 써주다
4  오늘 은 비 와 함께 돌아가다 길 추다 추다 직장 이 끝나다 제일 처음 생각 은 당...

In [7]:
labels = open('partial_label', encoding='utf-8').read().split('\n')

In [8]:
print(len(train_set))
print(len(labels))

1276677
1280001

In [9]:
train_set[1] = labels[:1276677]

In [10]:
train_set.head()

                                                   0      1
0  신곡 첫 해금 발매 히프 노 시스 마이크 권 완성 한정판 에 수록 되다 지로 이 시...  1f3a7
1               내 친구 어디 있다 나 는 슬프다 나르다 위로 하다 수 있다 부디  1f3a7
2                                             레드 벨벳   1f3a7
3                                       앞 으로도 많이 써주다  1f3a7
4  오늘 은 비 와 함께 돌아가다 길 추다 추다 직장 이 끝나다 제일 처음 생각 은 당...  1f3a7

In [11]:
len(train_set)

1276677

In [12]:
train_set[:100000].to_csv('train_set.tsv',sep='\t', encoding='utf-8', header=None, index=False)